$('.owl-carousel').owlCarousel({
    loop:true,
    margin:20,
    nav:true,
    responsive:{
        0:{
            items:1
        },        
        500:{
            items:5
        },        
        1000:{
            items:5
        }
    }
})